apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - name: "api-port"
      port: 9000
      targetPort: 9000
      nodePort: 30000
      protocol: TCP
    - name: "console-port"
      port: 9010
      targetPort: 9010
      nodePort: 30030
      protocol: TCP
  selector:
    app: minio
