apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: knative-ml-service
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: dev.local/knative_ml_services:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: project-configmap
